image: mcr.microsoft.com/dotnet/sdk:9.0-preview

stages:
  - build
  - test

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"

before_script:
  - 'dotnet restore'
  - 'dotnet tool update --global dotnet-ef'

build_job:
  stage: build
  script:
    - 'dotnet build --configuration Release'

test_job:
  stage: test
  script:
    - 'dotnet test PracticePlanFact2025.Tests/PracticePlanFact2025.Tests.csproj --no-build --configuration Release'
